---
- name: Deploy Cloudflare Tunnel
  hosts: cloudflare-tunnel
  roles:
    - role: docker_app
      vars:
        docker_app_name: cloudflare-tunnel
        docker_app_compose_src: "{{ playbook_dir }}/../../docker/cloudflare-tunnel/docker-compose.yml"
        docker_app_env:
          CLOUDFLARE_TUNNEL_TOKEN: "{{ cloudflare_tunnel_token }}"
