services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_SCANSCHEDULE: ${ND_SCANSCHEDULE}
      ND_LOGLEVEL: ${ND_LOGLEVEL}
      TZ: ${TZ}
    volumes:
      - navidrome_data:/data
      - /data/music-1:/music/pool1:ro
      - /data/music-2:/music/pool2:ro
    ports:
      - "4533:4533"

volumes:
  navidrome_data:
